# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fc008e46c71b52ad3b059e7bd64f32e20a52b276e8789477a13e291cb73916e8b5a89fcf3a5b66d522f58573e542e4e5228b28c62b4799e6a7aa25185728b0d

test:
  secret_key_base: dee6751104be39802140d485b7359116021e4281460e51184ecfc52966293791f53ad69942c8198a98127aba3c33c8032cafffb32d893e4a50e960ef0db1284f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
